image: registry.gitlab.tugraz.at/dbp/nextcloud/webapppassword/main:v1

stages:
  - test

.test_defaults: &test_defaults
  script:
    - echo "CORE_BRANCH=${CORE_BRANCH}"
    - NC_TMP=$(mktemp -d -t ci-XXXXXXXXXX)
    - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH $NC_TMP
    - mkdir $NC_TMP/apps/webapppassword
    - cp * $NC_TMP/apps/webapppassword -R
    - cd $NC_TMP
    - mkdir data
    - php7.4 ./occ maintenance:install
      --admin-user="admin"
      --admin-pass="admin"
      --database "sqlite"
      --database-name="oc_autotest"
      --database-user="oc_autotest"
      --database-pass="oc_autotest"
    - php7.4 ./occ app:enable webapppassword
    - php7.4 -S localhost:8080 &
    - cd apps/webapppassword
#    - php7.4 /usr/local/bin/composer install
#    - php7.4 /usr/local/bin/composer run cs
    - php7.4 /usr/local/bin/composer require --dev christophwurst/nextcloud:dev-${CORE_BRANCH}
#    - php7.4 /usr/local/bin/composer run psalm
    - make test
  after_script:
    - '[ -z "$NC_TMP" ] || rm -Rf $NC_TMP'

nc18:
  stage: test
  variables:
    CORE_BRANCH: "stable18"
  <<: *test_defaults

nc19:
  stage: test
  variables:
    CORE_BRANCH: "stable19"
  <<: *test_defaults

nc22:
  stage: test
  variables:
    CORE_BRANCH: "stable22"
  <<: *test_defaults

nc23:
  stage: test
  variables:
    CORE_BRANCH: "stable23"
  <<: *test_defaults

nc24:
  stage: test
  variables:
    CORE_BRANCH: "stable24"
  <<: *test_defaults

nc25:
  stage: test
  variables:
    CORE_BRANCH: "stable25"
  <<: *test_defaults
