version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - 8081:80
    environment:
      - WEBPASSWORD_ORIGINS=http://127.0.0.1:8001,http://localhost:8001
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=mydb
    volumes:
      - nextcloud:/var/www/html
      - ..:/var/www/html/custom_apps/webapppassword
      - ./nextcloud/certificates:/var/www/.nextcloud/certificates
      - ./nextcloud/sign-app.sh:/var/www/sign-app.sh
      - ./webapppassword.config.php:/var/www/html/config/webapppassword.config.php

volumes:
  nextcloud:
